### PR TITLE
Drop apiextensions

### PR DESCRIPTION
**Pull request by fiunchinho**
Towards https://github.com/giantswarm/giantswarm/issues/21301

## Checklist

- [X] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by fiunchinho** [comment]
@giantswarm/team-rocket I'd like to remove the `apiextensions` dependency from `standup`. Would it be fine to remove [this `kvm` specific logic](https://github.com/giantswarm/standup/blob/master/cmd/cleanup/runner.go#L153-L178) on `standup` next release?

**Comment by tfussell** [comment]
> @giantswarm/team-rocket I'd like to remove the `apiextensions` dependency from `standup`. Would it be fine to remove [this `kvm` specific logic](https://github.com/giantswarm/standup/blob/master/cmd/cleanup/runner.go#L153-L178) on `standup` next release?

This is still important for KVM testing. Instead of removing it, we could check for existence by fetching it as a `meta.PartialObjectMetadata` using the controller-runtime client.

**Review by kubasobon — APPROVED** [review]
Please re-request us once it's ready for review.

**Review by kubasobon — COMMENTED** [review]
fix

**Review by kubasobon — COMMENTED** [review]
Please re-request if it moves fwd.

**Comment by fiunchinho** [comment]
I have no focus on this at the moment, so I'm closing it.

**Pull request closed without merging**
