### PR TITLE
Add `--mode` flag to the `create release` command

### PR DESCRIPTION
**Pull request by whites11**
Towards: https://github.com/giantswarm/giantswarm/issues/14534

This PR adds a new flag `--mode` to the `create release` command.

The flag can be either `releases` or `azure-operator`.

If `releases`, the behaviour is the same as before.
If `azure-operator`, the `release` CR is created by copying the latest release available in the passed `releases` repo for `azure` and updating `azure-operator` component to the sha version of the passed repository.

### CODE REVIEW

**Review by tuommaki — APPROVED** [review]
From UX point of view this is not very intuitive or elegant, but the functionality seems fine.

**Comment by whites11** [comment]
> From UX point of view this is not very intuitive or elegant, but the functionality seems fine.

Do you mean the flag name is not easy to understand? If you have an alternative idea I'm happy to implement it

**Comment by tuommaki** [comment]
> Do you mean the flag name is not easy to understand? If you have an alternative idea I'm happy to implement it

Well the flag name is one thing, but it's mostly style issue and I don't have better idea for that.

Maybe bigger thing for me is that the semantics of the command change quite a bit with the flag:
- By default it creates a copy of the release submitted in the PR with only name changed. This is provider independent and generally rather straightforward.
- With flags, it creates Azure specific release from the latest one and changes the contents of it for Azure specific operator.
  - Is _latest_ release the absolute latest from the branch (meaning the diff if there's new release) or is it the latest that can be found from `master` with `active: true`?
  - What happens when `azure-operator` gets split into multiple operators?
 
Now that I'm thinking this, could we implement this behavior with slightly different strategy:
- In the pipeline that is used for `azure-operator` e2e tests:
  - Trigger specific pipeline from `azure-operator` CI
  - Have an additional task:
    - Clone `releases` repo - vanilla `master` or optionally branch maybe?
    - Run a command to create a new release in-place. Similar to `opsctl release deploy` but effectively in-place. On-disk version of `releases` checkout would now be changed.
      - `opsctl` already has functionality, but it would need some changes. Alternatively there could maybe be `standup prepare release` command for this?
  - Create release in management cluster with off-the-shelf `standup create release` without additional changes to specific command.
  - ...continue with rest of the "normal" pipeline.
 
@fiunchinho Do you think something like above could be possible? Can the "dirty" repo clone persist from one task to another?

WDYT about that alternative approach?

**Comment by whites11** [comment]
> * Trigger specific pipeline from `azure-operator` CI

If we have a specific pipeline for this use case, why don't we simply create a different task for creating the release?
It can simply opsctl to create the release as you suggested and apply it straight away, skipping `standup` all the way down.

The thing I don't like about this is that we will not be able to use `/test azure` but we would need a different trigger.

**Pull request closed without merging**
